# Generated by Django 6.0.4 on 2026-06-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_voice_character_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='enable_voice_output',
            field=models.BooleanField(default=False),
        ),
    ]
